### ISSUE TITLE
What role should the Wiki play in the Cornell CS community?

### ISSUE THREAD

**Issue by rishi1999** [CornellCSWiki/CornellCSWiki#89]
The primary function of the CS Wiki is to be a resource for learning about CS classes offered at Cornell. There exists other content as well, but the vast majority of the content is class specific.

Most of the class pages have more-or-less the following structure:

- General Information
- Prerequisites
- Topics Covered
- Workload
- Testimonials
- Past Offerings

_General Information_, _Prerequisites_, and _Topics Covered_ contain information that is largely just ported over from publicly available course websites.

The remaining sections cover the workload of the class, general opinions, advice, and feedback related to the class, professor name, semester taken, and median of the course. With the exception of the median, all of this information would be included in a course review site like [CU Reviews](cureviews.org) (managed by Cornell DTI).

The years of content we have are certainly valuable, but what reason is there to encourage students to provide new information here rather than on CU Reviews? On that site, they would not need to deal with the hassle of creating PRs and could easily contribute anonymously. Possible fixes to those problems are discussed in #80, but the solution is already implemented on CU Reviews.

If the only new information the Cornell CS Wiki is providing is course medians, perhaps it would be better for the Wiki to go into a conservation/archive mode, where we retain all the existing information and continue to host the site, but encourage users to contribute to CU Reviews instead of adding info here. It will also be useful to students if course information is consolidated in one place, so they do not have to peruse multiple sources.

(side note -- a project dedicated to just collecting the medians of courses at Cornell would be pretty interesting)

Thoughts on this proposal? I've been thinking about it on and off for some time, and continuing to 'compete' with CU Reviews and similar sites doesn't seem practical or helpful to the community overall.

**Comment by kungpaogao** [comment]
These are valid points. I'm obviously biased (as a member of DTI), but I do think CUReviews provides a lower barrier to entry for the majority of people. I also agree with the idea that it's a good idea to have content consolidated into one place.

I personally found the site to be useful for getting a general sense of classes and potential paths, especially before I found the CS major pages, CUReviews, etc. And, I do think the format of the class pages do lend themselves to getting a good sense of what to expect from courses (as compared to other websites).

In terms of the future of the site, maintenance mode would be nice because I still think most of the information is still relevant. I think the Wiki has the ability to be a more consolidated place *specifically* for the CS major. To me, this means like maybe compiling relevant Cornell subreddit or CS 0000 (Piazza) posts for each class.

Regarding the side note, I know there's a spreadsheet that tracks medians that is floating around the subreddit, and there's an effort to collect grades at the end of each semester.

**Comment by rishi1999** [comment]
Thanks for the response. I'm a bit overwhelmed with work right now, but perhaps we can talk more about this after the semester is over?

**Comment by rishi1999** [comment]
Since there haven't been any opposing viewpoints expressed since we last spoke, I think it makes sense to move forward with this plan.

I'm thinking we could put a message at the top of the homepage like the following:

> The Wiki is currently in conservation mode: all content is being maintained, but we are no longer actively seeking new submissions. If you find any errors or misleading information, please let us know or submit a pull request. If you would like to contribute advice or information on a particular course, we recommend that you submit your review to [Rate My Professors](https://www.ratemyprofessors.com/) or [CU Reviews](https://www.cureviews.org/). If you are looking for up-to-date information on courses, we recommend checking the [Class Roster](http://classes.cornell.edu/), the [CS 0000](https://gmail.us20.list-manage.com/track/click?u=afdc8af6452afba83982af960&id=8bbcc79f0f&e=34a0f53301) Piazza forum, and the [r/Cornell](https://www.reddit.com/r/Cornell/) subreddit.

**Comment by kungpaogao** [comment]
Yah, I think that sounds good. Of course, it's also possible that the Wiki could evolve in the future, since it's all open source anyways :)

**Comment by rishi1999** [comment]
Do you want to whip up some CSS magic to display that message on the homepage? If you're too busy, I can have a go at it.

**Comment by kungpaogao** [comment]
yup, I can put together something in the next few days

**Comment by rishi1999** [comment]
That was really fast - thanks for implementing that!
